### ISSUE TITLE
User Can View a List of Pokemon

### ISSUE THREAD

**Issue by tiffanydbrown** [tiffanydbrown/catch-em-all#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to see all Pokemon from Generation 1. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to view a list of Pokemon (10 at a time) in numerical order. If they would like to view more, they will be able to click a button ("Load More") to see additional Pokemon.  

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2023-11-27 at 3 01 17 PM](https://github.com/tiffanydbrown/ajax-project/assets/139157669/cd72a27b-d9c3-414d-9c1f-9485dbec7a34)
![Screenshot 2023-11-27 at 3 01 37 PM](https://github.com/tiffanydbrown/ajax-project/assets/139157669/b14a1683-de5e-4763-a4d4-bec7f4695a42)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create  `main.js` and `styles.css` files.
- [x] Create an HTML skeleton, and link the JSON, CSS, and JS files to the `index.html` file.
- [x] Open the `index.html file` in the browser.
- [x] Add a `div[data-view="pokedex"]` to the HTML.
- [x] Add a `pokemon-container` to the HTML
- [x] Create a homepage layout that looks exactly like the wireframe.
- [x] Set-up local storage.
- [x] In `main.js`, query the DOM for the `.pokemon-container`, the button elements, and the view elements.
- [x] Listen for a `click` event on the Load More button:
  - [x] Checks to see if the event.target matches `.pokemon-container` to ensure that the user has to actually click on the `Load More` button to load 10 additional Pokemon. If it does match, then...
  - [x] Loop through the `NodeList` of `pokemon` elements and compare each of them to the event.target. The element that equals the event.target should have its className updated to make it `.active`. All others should not be made `.active`.
- [x] Add code to your event listener callback function to do the following only if a `Load More` was clicked: 
  - [x]  Get the value of the `data-view` attribute of the event.target and put it in a variable.
  - [x] Loop through the `NodeList` https://developer.mozilla.org/en-US/docs/Web/API/NodeList of `.view elements` and compare each of their `data-view` attribute values to the variable declared in the previous step. All `.view` elements should be `.hidden` except the one that has a `data-view` attribute that equals the variable declared in the previous step.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
