### ISSUE TITLE
User can click on an entry to view the details of a Pokemon.

### ISSUE THREAD

**Issue by tiffanydbrown** [tiffanydbrown/catch-em-all#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click on a Pokemon card to view more details about the Pokemon.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to view more information about each Pokemon not shown on the main card on homepage.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2023-11-30 at 9 25 10 AM](https://github.com/tiffanydbrown/ajax-project/assets/139157669/e6690360-d3be-4472-91d3-4f6ea39f7877)
![Screenshot 2023-11-30 at 9 24 54 AM](https://github.com/tiffanydbrown/ajax-project/assets/139157669/fe4a9cdd-76ab-4a47-a22a-fd691afae471)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a `modal-view` in the HTML.
- [x] Add a `click` event listener to create a modal.
  - [x] Show a `Pokemon Stats Card modal` when the user `clicks` a Pokemon card on the home screen.
  - [x] Request the API to call the Pokemon when a card is clicked.
  - [x] Loop through the array to find the correct `ID #`.
  - [x] Make a condition that the index must match the `ID` of the clicked card.
  - [x] Create a `DOM tree` to create the new Pokemon Stats Card.
- [x] Hide the modal when the user clicks `EXIT`.
  - [x] Create an event listener that will hide the modal when the button is clicked and switch the view from the `modal-view` to the `Pokedex` view.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
